### ISSUE TITLE
after test, can't show video to surfaceview

### ISSUE THREAD

**Issue by githubuse** [htwahzs/Rtsp-Android-Client#1]
hi,
I have did more test(connect my own h264 rtsp url and other rtsp server), but can't show video, from my log , i can see client could receive data, but  inputBufferIndex = mMeidaCodec.dequeueInputBuffer(2000); always return -1.   test url :rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp, also tested for my rtsp url in my local wifi.
Look forward your reply !
Thanks

**Comment by htwahzs** [comment]
MediaCodec can only be used after android 4.1
